version: '3'

services:
  #PHP Service
  app:
    build: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis
    env_file: .env

  #Nginx Service
  nginx:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - app

  #Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "33600:3306"
    environment:
      - MYSQL_DATABASE=laravel-app
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./.docker/dbdata/:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

