version: '3'

services:
  #PHP Service
  app:
    build: .
    container_name: app

  #Nginx Service
  nginx:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"

  #Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379

