version: '3'

services:
  #PHP Service
  app:
    build: .
    container_name: app

  #Nginx Service
  nginx:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"

  #Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379

  #MySQL Service
  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "33600:3306"

